### ISSUE TITLE
BUG: Verbindung nicht möglich

### ISSUE THREAD

**Issue by socram70** [jlawyerorg/j-lawyer-tbaddon#11]
Eine Verbindung ist trotz korrekter Parameter nicht möglich. Ich habe bereits folgendes probiert:

https://192.168.25.105:8080
http://192.168.25.105:8080
192.168.25.105:8080
192.168.25.105

Mein Nutzername besteht aus Vor- und Nachnamen mit einem Leerzeichen dazwischen. Außerdem gibt es im Nachnamen ein Sonderzeichen.

**Comment by j-dimension** [comment]
@iradraconis man könnte in options.js beim Klicken des saveButton bereits einen Dummy-Rest-Request absetzen, an einen Endpunkt der keine großen Berechtigungen benötigt. Dann wären Verbindung und Nutzerdaten gleich verifiziert.

**Comment by iradraconis** [comment]
> @iradraconis man könnte in options.js beim Klicken des saveButton bereits einen Dummy-Rest-Request absetzen, an einen Endpunkt der keine großen Berechtigungen benötigt. Dann wären Verbindung und Nutzerdaten gleich verifiziert.

gute Idee. Wenn gar keine Verbindung zum Server besteht kann der Nutzer so erstmal ein Feedback erhalten.

**Comment by socram70** [comment]
Das Problem ist jetzt behoben, danke!

**Comment by socram70** [comment]
Gut möglich, dass das an dem Sonderzeichen liegt? Testweise habe ich direkt zwischen beiden Accounts mit komplett gleichen Rechten und gleichem Kennwort gewechselt. Mit Nachnamen und Sonderzeichen geht es nicht, ohne Nachnamen sofort. Melde dich gerne, wenn ich irgendwie mit Tests helfen kann.

**Comment by iradraconis** [comment]
> Gut möglich, dass das an dem Sonderzeichen liegt? Testweise habe ich direkt zwischen beiden Accounts mit komplett gleichen Rechten und gleichem Kennwort gewechselt. Mit Nachnamen und Sonderzeichen geht es nicht, ohne Nachnamen sofort. Melde dich gerne, wenn ich irgendwie mit Tests helfen kann.

Kannst du mir testweise den Anmeldenamen per Mail schicken? Dann kann ich das testen und das ggfs. schon so lösen...

**Comment by j-dimension** [comment]
Handelt es sich bei dem / den Sonderzeichen um einen Doppelpunkt?

**Comment by socram70** [comment]
Ich habe ein wenig weitere Fehlersuche betrieben und einen weiteren Account mit Vor- und Nachnamen angelegt und hier statt ä mit ae gearbeitet. Damit funktioniert die Ablage. Nach dem Umstellen auf den ä-Account dann nicht mehr. Ohne, dass ich Erfahrung mit Thunderbird-Extensions hätte würde ich da mal auf ein Problem mit der Codierung des Umlauts tippen.

**Comment by iradraconis** [comment]
die Eingabe erfolgt eigentlich in UTF8 Codierung. Hat der Server eventuell ein anderes Schema eingestellt?
