### ISSUE TITLE
Verschlüsselte Nachrichten zur Akte speichern

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-tbaddon#13]
Wenn man im Thunderbird PGP nutzt, wäre es toll wenn verschlüsselt empfangene, aber bereits zur Anzeige entschlüsselte, Nachrichten auch unverschlüsselt in die Akte gelangen würde. 

Derzeit wird die verschlüsselte Nachricht gespeichert.

**Comment by iradraconis** [comment]
aktuell noch nicht möglich in Thunderbird. Ich habe es im Entwicklerforum mal als Ticket erstellt...

https://bugzilla.mozilla.org/show_bug.cgi?id=1854684

**Comment by librelegal** [comment]
Ich nutze viel Verschlüsselung, wäre auch für mich wichtig ...

**Comment by iradraconis** [comment]
Laut Bug Tracker soll das in Milestone 125 eingefügt worden sein. 

@j-dimension hast du eventuell eine Version von Thunderbird >= 125 installiert und hast das schon testen können? 

Wir müssten schauen, ob die Erweiterung dann angepassten Code benötigt, oder ob es ohne Anpassung funktioniert.

**Comment by j-dimension** [comment]
So brand-new bin ich leider nicht :-(   Meine Distribution hat aktuell die 115 im Repository.

**Comment by iradraconis** [comment]
Ab Thunderbird 128 erhält getRawMessage decryption support. 
128 ist ein ESR Release und wird damit der Standard auch in konservativen Linux Distros.

let rawMessage = await messenger.messages.getRaw(messageData.id, { decrypt: true });

**Comment by iradraconis** [comment]
mit 1.0.8 implementiert
