### ISSUE TITLE
Thunderbirdplugin - Erstinstallation[BUG] 

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-tbaddon#16]
Wenn ich das Thunderbird-addon installiere, dann findet es auf meinen Rechnern die Akten erst, wenn man in den Einstellungen von https auf http umstellt. Dann werden die Akten gefunden. Danach kann man wieder Https einstellen. (Bisher bei mir so auf 4 Rechnern so gelaufen.....)

**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

**To Reproduce / Schritte zum Nachvollziehen**

1. Go to / Gehe zu '...'
2. Klicke auf / Click on '....'
4. Error message / Fehlermeldung: '...'

**Expected behavior / Erwartetes Verhalten**
Eine Beschreibung des erwarteten Verhaltens.

**Screenshots**
Falls relevant, Screenshot beifügen.

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem:
 - j-lawyer.org Version:

**Additional context / Sonstiges**

**Comment by iradraconis** [comment]
kein Bug
