### ISSUE TITLE
Enhancement: Prüfen ob Datei schon existiert (Speichern geht unendlich....)

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-tbaddon#19]
Nachdem meiin Addon heute morgen ging und ich gerade eine mail speichern wollte - geht jetzt wieder nix mehr. Die Verbindung wird wohl hergestellt, die Akten gefunden. Und dann hängt das Plugin in ... Speichern.... unendich....

**Comment by Mucki526** [comment]
als ich die betroffene mail dann per drag und drop in den dokumentenordner packen wollte, stellte ich fest, dass ich erst einen neuen Namen vergeben musste (irgendwo eine Leerstelle in den vorgegebenen Namen machen), da eine e-mail des Mandanten bereits denselben Namen trug. Ich denke da liegt das o.g. Problem. Die mail kann nicht gespeichert werden, weil eine namensgleiche mail bereits vorhanden ist.

**Comment by j-dimension** [comment]
@iradraconis es gibt einen separaten API-Endpunkt, um vorab auf Namenskollisionen zu prüfen. Melde Dich, wenn es Fragen gibt.
