### ISSUE TITLE
FEATURE: verschlüsseltes Speichern von Zugangsdaten

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-tbaddon#2]
aktuelle genutzt:
browser.storage.local

**Comment by librelegal** [comment]
Da nun die v.0.9.9.9 da ist und es zur Version 1.0 nicht mehr weit scheint, hege ich die Hoffnung, dass dieser issue davor noch angegangen werden kann ...

**Comment by iradraconis** [comment]
Die Extension wäre kaum noch zu gebrauchen, wenn bei jedem Öffnen des Popups oder von Thunderbird eine Passphrase einzugeben wäre. Siehe auch:

https://thunderbird.topicbox.com/groups/addons/Tc859ef36e0e4084c/securely-store-credentials

Um ein mögliches "Risiko" zu minimieren, kann aber für die Extension ein Nutzer eingerichtet werden, der nur über die nötigen Rechte verfügt. 

 @j-dimension Was sagst du dazu? (schau mal den Link an)

**Comment by j-dimension** [comment]
Wenn es keine built-in - Möglichkeit gibt, wird eine eigene Krypto auch keinen Sinn ergeben. Der genutzte API-Account kann beschränkt werden, ja.
