### ISSUE TITLE
Https geht nicht

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-tbaddon#20]
Ich habe jetzt festgestellt, dass bei uns das Adon nur funktioniert, wenn ich dauerhaft auf http: statt https: umstelle. Https geht garnicht (das war bei meiner letzten Meldung vom Problem vorhandener e-mail Name verhindert speichern) überlagert..... Im Moment läuft 0.9.7.5 mit http....

**Comment by j-dimension** [comment]
Ich zitiere einfach meinen Kommentar von Ticket #16:

Das Zurückstellen auf https bringt nichts. Sehr wahrscheinlich nutzt Dein Server kein https. Würdest Du nach dem Zurückstellen auf https nochmals die Akten laden wollen, wird das nicht funktionieren.

https ist für solche Installationen interessant, wo der j-lawyer auf einem Server im Rechenzentrum läuft und nur verschlüsselt kommuniziert.

**Comment by j-dimension** [comment]
https funktioniert, wenn die Gegenstelle es unterstützt. Das hier ist kein Bug.

**Comment by Mucki526** [comment]
O.k. war mir nicht klar, dass da am Server was umgestellt werden müsste. Das Plugin gibt bei der Einrichtung auf der Einrichtungsseite ein Beispiel mit https:... also gehe ich dasvon aus, dass sich das Plugin sich per https mit dem Server verbindet.... Sorry, dann habe ich das fehlinterpretiert. Ich stelle alles auf http:... um... Vorschlag - Beispiel auf http korrigieren..

**Comment by j-dimension** [comment]
Jo, das wäre wahrscheinlich für die meisten User passender.

**Comment by iradraconis** [comment]
Dann werde ich den Hinweis in den Optionen auf HTTP umstellen. :-)
