### ISSUE TITLE
Vorschlag für Suchfunktion im Addon auch "wegen" Zweck der Akte anzeigen

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-tbaddon#21]
Wenn man mit J-lawyer eine Akte sucht sieht man auch immer den Zweck "wegen"

1234 Müller ./. Müllerin wegen Trennungsunterhalt
1237 Müller ./. Müllerin wegen Zugewinn
1239 Müller ./. Müllerin wegen Sorgerecht

im addon sieht man den Zweck der Akte nicht, sondern nur Müller ./. Müllerin (und wenn man die Aktennummer nicht im Kopf hat... hat man verloren...) Vorschlag  auch das zugehörige "wegen" hinter der Akte anzeigen....

**Comment by iradraconis** [comment]
Done

**Comment by Mucki526** [comment]
Also bei mir zeigt die 9.7.6 jetzt den Aktennamen an, dahinter dann die Aktennummer in Klammer, aber nicht den Zweck.... Da stimmts noch nicht....

**Comment by iradraconis** [comment]
Ich habe jetzt hier eine Funktion eingebaut (anders geht es aus Performance Gründen nicht) wonach in der Ergebnisliste der Suche ein Tooltip angezeigt wird, wenn mit der Maus über eine Zeile gefahren wird. Das Tooltip zeigt "wegen" der Akte an. Das sollte die Zuordnung zur richtigen Akte erleichtern, wenn es viele Akten mit demselben Rubrum gibt. Gern testen.
