### ISSUE TITLE
Anzeigen des Zwecks der Akte

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-tbaddon#23]
Es funktioniert jetzt, wenn man eine Liste der Akten hat, dass man sie anklickt um zu sehen, um welche Akte es sich handelt. Aber wenn man 10 Akten hat und 9 x die falsche anklickt, weil man erst nach dem Anklicken weiss, welche man angeklickt hat, ist das suboptimal. Besser wäre es, wenn gleich mit dem Suchergebnis das "wegen" mit angezeigt wird. Oder, wenn das ein Platzproblem ist, dass statt dessen beim Überfahren der Akte ohne Maus in einem kleine Pop-up der Zweck eingeblendet wird (wie ein Kommentar).  Dann braucht man nicht jedesmal neu suchen und die nächste Akte mit Klick suchen um zu sehen, welche das ist....

**Comment by iradraconis** [comment]
Ja das wäre besser, war aber gerade nicht umsetzbar. Es gibt zwei verschiedene API Endpunkte, für die Auflistung der Fälle und deren Metadaten. Wie oft kommt es vor, dass 10 Akten identischen Namens angelegt werden? Meist sind es selbst im Familienrecht weniger.

**Comment by iradraconis** [comment]
Und warum neues Ticket? Der Wunsch war bereits in #21 formuliert.
