### ISSUE TITLE
Abspeichern blockiert durch geöffnete e-mail entwürfe

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-tbaddon#27]
Wenn man eine e-mail verfasst oder an mehreren Entwürfen arbeitet, dann ist die App nicht in der Lage, eine e-mail abzuspeichern, solange noch ein Entwurf offen ist....

**Comment by iradraconis** [comment]
Ja das ist richtig. Die Mail, die zur Akte gespeichert wird, bekommt von Thunderbird erst dann eine ID zugeordnet, mit der dann die Mail gespeichert werden kann, wenn sie auch versandt wurde. Daher die "krücke", dass beim Speichern noch zu sendender Mails das Speichern nach dem Senden vorgenommen wird. Lässt sich m.E. aktuell nicht anders lösen.

**Comment by iradraconis** [comment]
Ich habe mal versucht, das zu reproduzieren. Also: wenn mehrere Entwürfe offen sind, empfiehlt es sich, unmittelbar vor dem Senden, die Erweiterung zur Auswahl der Akte zu nutzen. Wenn dann aus einem anderen Entwurf gespeichert werden soll, muss dann dort unmittelbar vor dem Versenden die Akte ausgewählt und auf "speichern" geklickt werden. Vielleicht hilft das. Wenn nicht, muss ich noch mal schauen.

**Comment by iradraconis** [comment]
schließe hier, weil derzeit keine "Lösung" möglich....
