### ISSUE TITLE
Aufruf der APP 

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-tbaddon#28]
Ein kurzes Klicken auf den App-Eintrag in Thunderbird (rechte Taste Maus) reicht nicht, man muss die Taste laange drücken. Auch ist es zumindest bei mir so, dass ich mit dem Mauszeiger nicht irgendwo im Button sein darf, sondern etwas oberhalb der Mitte des Buttons...

**Comment by iradraconis** [comment]
Ich kann das nicht reproduzieren. Warum rechte Maustaste? Alle Aktionen, bis auf die Mehrfachselektion werden mit linker Maustaste ausgewählt. Welcher "App-Eintrag"? Der Button mit dem Namen "Email an j-Lawyer senden"? Oder was ist gemeint?

**Comment by iradraconis** [comment]
@Mucki526 Kannst du mehr Infos geben?

**Comment by iradraconis** [comment]
Ich schließe mangels Feedback
