### ISSUE TITLE
Aktensuche

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-tbaddon#29]
Manche Akten und Aktenzeichen werden einfach nicht gefunden, vor allem, wenn man über die Aktennummer sucht oder einen Teil des Aktennamens eingibt (nicht von Anfang an).

**Comment by iradraconis** [comment]
Das kann ich nicht reproduzieren. Bitte bedenken, dass Akten, die nach dem letzten Aktualisieren hinzugefügt wurden, von dem AddOn nicht verarbeitet werden können, daher ab und zu mal auf "aktualisieren" klicken. Die Suche funktioniert bei mir Mit dem Namen, auch Teile davon und dem Aktenzeichen.

**Comment by iradraconis** [comment]
Welches Format haben die Aktenzeichen?

**Comment by iradraconis** [comment]
@Mucki526 Kannst du mehr Infos geben?

**Comment by iradraconis** [comment]
Schließe mangels Feedback
