### ISSUE TITLE
Version in den Einstellungen anzeigen

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-tbaddon#3]
Solange das Addon nicht über die offiziellen Quellen installiert werden kann, wäre es cool eine Versionsanzeige zur Verfügung zu haben. Im Fall von Nutzeranfragen könnte man so schnell unterscheiden zwischen 

"muss ich mir anschauen" und "bitte erstmal die neueste Version installieren"

**Comment by iradraconis** [comment]
Die Version wird bereits in der Übersicht der installierten Erweiterungen in Thunderbird angezeigt. Soll die Versionsnummer darüber hinaus auch im Optionen Dialog angezeigt werden?

**Comment by j-dimension** [comment]
Ah, hab's gefunden! Das reicht vollkommen.
