### ISSUE TITLE
Abspeichern sehr träge

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-tbaddon#30]
Das Abspeichern einer mail dauert wahnsinnig lange. Drag and Drop einer mail in den Dokumentenordner geht rasend schnell.... Das müsste doch auch beim Abspeichern schneller gehen.

**Comment by iradraconis** [comment]
Was heißt "wahnsinnig lange"? Ich kann das hier so ohne weiteres nicht reproduzieren.

**Comment by iradraconis** [comment]
@Mucki526 Kannst du mehr Infos geben?

**Comment by iradraconis** [comment]
ich schließe mangels Feedback.
