### ISSUE TITLE
Auswahl der mails die zu migrieren sind.

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-tbaddon#34]
bei mir ist es so, dass ich regelmäßig zweimal auf die mail klicken muss, um sie migrieren zu können. Beim ersten mal passiert nichts. Und ich muss den Mauszeiger an den oberen Rand der mail bewegen. Wenn die Mauszeigerspitze auf die Mitte der mail zeigt, geht auch nichts.

**Comment by iradraconis** [comment]
@Mucki526 was ist gemeint mit: "regelmäßig zweimal auf die mail klicken muss, um sie migrieren zu können".
Das klingt insgesamt nicht nach einem "bug" der Erweiterung. Welche Thunderbird Version ?

**Comment by iradraconis** [comment]
schließe mangels Feedback
