### ISSUE TITLE
Keine Verbindung wenn Tunnel über SSH verwendet wird

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-tbaddon#35]
VPN funktioniert. 

SSH führt zu "Uncaught TypeError: NetworkError when attempting to fetch resource"

**Comment by j-dimension** [comment]
Die Requests werden von Thunderbird blockiert:

![grafik](https://github.com/jlawyerorg/j-lawyer-tbaddon/assets/3729754/304c18dd-8554-4b85-a962-4e88b3208ae8)

**Comment by j-dimension** [comment]
Es hat irgendetwas mit CORS zu tun (Cross-Origin Resource Sharing)

![grafik](https://github.com/jlawyerorg/j-lawyer-tbaddon/assets/3729754/427e9a6d-003d-418f-ab8d-f27621293ebf)

**Comment by j-dimension** [comment]
Hab ein wenig recherchiert und es könnte eine Permission im Manifest helfen:

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions

**Comment by j-dimension** [comment]
Das AddOn nutzt ein Manifest in Version 2, dort gibt es noch keine host_permissions wie es sie in V3 gibt:

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/host_permissions

**Comment by j-dimension** [comment]
Im Manifest sehe ich ein solches Snippet:

```
  "permissions": [
    "activeTab",
    "tabs", 
    "messagesRead",
    "compose",
    "storage", 
    "<all_urls>",
    "messagesTags",
    "menus"
  ],
```

Ich weiß nicht genau was all_urls bedeutet, und ob es auch bedeutet dass Requests auf localhost erlaubt werden.

**Comment by iradraconis** [comment]
@j-dimension  Ich schaue mir das heute Abend mal an. Danke fürs Recherchieren. Ich weiß nicht, ob ich das Manifest schon auf v3 setzen kann. Ich würde dir dann eine Test-Version zukommen lassen.

**Comment by iradraconis** [comment]
> Kann man die .XPI einfach auspacken, das Manifest bearbeiten, neu zippen und dann neu im Thunderbird installieren?

Genau so! Aber ich würde vorher das alte "deinstallieren" also aus Thunderbird "entfernen" (so heißt es glaube ich dort).

**Comment by iradraconis** [comment]
Ich glaube aber, dass das mit all_urls schon abgedeckt ist. Bin gespannt, was dein Test ergibt.

**Comment by j-dimension** [comment]
Die Erweiterung des Manifests bringt erstmal keine Änderung. Ich schaue weiter.

**Comment by iradraconis** [comment]
Ich habe mal im Thunderbird Forum ein Ticket hinterlassen.

**Comment by j-dimension** [comment]
Gelöst. Notwendige Einstellung in Thunderbird:

- Menü "Bearbeiten"
- "Einstellungen"
- ganz nach unten scrollen
- "Konfiguration bearbeiten"
- In der Suche folgenden Wert eintragen: network.security.ports.banned.override
- anschließend "String" auswählen und den gewünschten Port eintragen (bei Verwendung eines SSH-Tunnels im j-lawyer.org Clientprofil ist es jener Port, der im dritten Eingabefeld (hinter "Port") steht
- den Wert mit Klick auf den Haken speichern

Ein Neustart von Thunderbird ist nicht notwendig.

**Comment by j-dimension** [comment]
> Ich habe mal im Thunderbird Forum ein Ticket hinterlassen.

Wow, Du warst zu schnell. Ich hab eine Einstellung gefunden.

**Comment by j-dimension** [comment]
Ich kann das auch übernehmen, wenn Du magst. 

Ja, aus meiner Sicht können wir hier schließen.
