### ISSUE TITLE
Geschindigkeit des Speicherns

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-tbaddon#37]
Das speichern aus dem Adon geht bei mir unendlich langsam. Mit Drag und drop gehts in Sekundembruchteil. Wäre es nicht eine Idee, dass das Addon genau diese Drag-und-Drop Routine benutzt, wenn sie verfügbar ist (also den Mechanismus, der die Mail in den Dokumentenordner transportiert) oder eine andere Routine falls verfügbar und auf das mailen nur zurückgreift, wenn das nicht möglich ist. Ich habe mich mit dem Mechanismus des Addons nicht auseinandergesetzt, hoffe ich frage nix blödes...

**Comment by iradraconis** [comment]
Duplikat von #30 , auch Dein Ticket und wo leider auch kein Feedback gekommen ist.
