### ISSUE TITLE
bug ssh? beim öffnen

### ISSUE THREAD

**Issue by SaschaKarcher01** [jlawyerorg/j-lawyer-tbaddon#42]
Die  .eml wird  in dem Ordner gespeichert und man kann auch im rechten Vorschaubild die Vorschau sehen,
jedoch wird dann beim Öffnen der .eml oder externen Öffnen der Fehler angezeigt:
"Dokument kann nicht geöffnet werden .....Die Syntax für den Dateinamen,Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch"

**Comment by j-dimension** [comment]
Wie lautet der Dateiname?

**Comment by SaschaKarcher01** [comment]
![Screenshot 2024-01-24 124223](https://github.com/jlawyerorg/j-lawyer-tbaddon/assets/78957183/2b944a08-189c-495c-bc46-0e15ca6af711)

**Comment by SaschaKarcher01** [comment]
wenn ich die Datei umbenenne geht es dann

**Comment by j-dimension** [comment]
Wenn der Client ein Windows ist, wird das ? und das @ ein Problem. Müssen überlegen, ob das Plugin eine Dateinamenbereinigung macht, oder zentral der j-lawyer-Server. Oder ob das erst beim Öffnen des Dokuments passiert.

**Comment by SaschaKarcher01** [comment]
Konstellation ist hier Linux Server/Win 11 Client

**Comment by iradraconis** [comment]
Ich schaue mir das heute Abend an.. vielleicht kann ich kurzfristig eine neue Version bereitstellen

**Comment by iradraconis** [comment]
Über welchen Teil des Addons wird die Nachricht zur Akte gespeichert? Per Rechtsklick in der Nachrichtenliste? Nach Versand einer Nachricht? Oder über den Button, der oberhalb der Nachricht angezeigt wird?

**Comment by SaschaKarcher01** [comment]
Der Fehler wird erst nach dem Weiterleiten innerhalb von jlawyer angezeigt. Dabei ist egal ob zuvor per  Rechtsklick oder durch dem Button über der Nachricht das Doikument an jlawyer übertragen wurde.

**Comment by SaschaKarcher01** [comment]
....es reicht dann komischerweise in jlawyer aus, einmal mit rechtsklick auf umbenennen zu klicken, ohne tatsächlich dann das Dokument umzubennenen

**Comment by SaschaKarcher01** [comment]
wow. läuft jetzt perfekt. vielen Dank. Ticket kann geschlossen werden.
