### ISSUE TITLE
BUG: Kalender auflisten nicht für jeden Nutzer möglich, Rechteproblem?

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-tbaddon#46]
Gerade beim Test der 0.9.9.8 aufgefallen. 

Es sollte möglich sein, alle Kalender aufzulisten mit einem Nutzer, der Zugriff auf alle Kalender hat. Wenn der Nutzer keinen Zugriff auf alle Kalender hat, muss hierfür noch eine Lösung implementiert werden, die den Fehler abfängt. 

Das Addon könnten andernfalls nur Anwender nutzen, die volle Admin Rechte haben. Zumindest für die Kalendereinträge.

**Comment by iradraconis** [comment]
![grafik](https://github.com/jlawyerorg/j-lawyer-tbaddon/assets/71747937/ec053257-f8b0-4dc4-8af3-ef5d1829a294)

**Comment by j-dimension** [comment]
https://github.com/jlawyerorg/j-lawyer-org/issues/2300

**Comment by iradraconis** [comment]
fixed in V 0.9.9.9 und j-Lawyer.org 2.6
