### ISSUE TITLE
BUG: Upload schlägt fehl bei großen Anhängen

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-tbaddon#47]
background.js 

111: Uncaught (in promise) SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

browser.storage.local.get("selectedTags").then(result => {
                console.log("selectedTags: " + result.selectedTags);
            }

116: Error: TypeError: NetworkError when attempting to fetch resource.

117: Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.

**Comment by j-dimension** [comment]
Man kann das konfigurieren in wildfly/configuration/standalone.xml

bspw. 
max-post-size="25485760"
um 25MB zu erlauben.

```
        <subsystem xmlns="urn:jboss:domain:undertow:12.0" default-server="default-server" default-virtual-host="default-host" default-servlet-container="default" default-security-domain="other" statistics-enabled="${wildfly.undertow.statistics-enabled:${wildfly.statistics-enabled:false}}">
            <buffer-cache name="default"/>
            <server name="default-server">
                <http-listener name="default" max-post-size="25485760" socket-binding="http" redirect-socket="https" enable-http2="true"/>
                <https-listener name="https" max-post-size="25485760" socket-binding="https" ssl-context="applicationSSC" enable-http2="true"/>
                <host name="default-host" alias="localhost">
                    <location name="/" handler="welcome-content"/>
                    <http-invoker http-authentication-factory="application-http-authentication"/>
                </host>
            </server>
```

Ich werde das Default auf 50MB anheben.

**Comment by iradraconis** [comment]
Danke Jens!

**Comment by iradraconis** [comment]
Ich habe das ausprobiert. Mit der Anpassung in der standalone.xml funktioniert alles, wie es soll.
