### ISSUE TITLE
Herunterladen der Daten

### ISSUE THREAD

**Issue by RAStangier** [jlawyerorg/j-lawyer-tbaddon#48]
Hallo,

ich habe mich sehr über die Nachricht über das Thunderbird-Add On gefreut. Leider funktioniert das Herunterladen der Daten derzeit noch nicht. In folgendem Schritt der Installationsanleitung:

"- Daten vom Server laden - Klick auf das Pfeil Icon in der Erweiterung"

fehlt das genannte Pfeil Icon bei mir. Somit funktioniert auch die Suche nach Akten logischerweise nicht. Kennen Sie das Problem bzw. was mache ich vielleicht falsch?

Herzlichen Dank für Ihre Rückmeldung im Voraus und viele Grüße

**Comment by iradraconis** [comment]
Das Pop-up Fenster für das addon kann gescrollt werden

**Comment by RAStangier** [comment]
Danke für die Rückmeldung. Ist es der kreisförmige Pfeil, bei dem dann "Daten aktualisiert" erscheint? Wenn ja, führt das jedenfalls bei mir dennoch nicht dazu, dass Aktenzeichen etc. gefunden werden.

**Comment by iradraconis** [comment]
Ja der Button ist richtig. Sind die Verbindungsdaten in den Einstellungen korrekt eingegeben?

**Comment by RAStangier** [comment]
Ich kann keinen Fehler finden. Allerdings muss ich jedes Mal erneut bei den Einstellungen "Speichern" auswählen, sodann erscheint dort "Login gespeichert". Wenn ich das Fenster dann schließe und erneut aufrufe, kann/muss ich wieder "Speichern" auswählen.

**Comment by iradraconis** [comment]
Die Daten sind gespeichert beim ersten Versuch. Gerade beim Server kann sich ein Tippfehler einschleichen http:// sollte voran gestellt werden.

**Comment by RAStangier** [comment]
Das fehlende "http://" war der zugegebenermaßen dumme Fehler. Ich danke herzlich für Ihre Hilfe!
