### ISSUE TITLE
Schlagwörter an Mail in Thunderbird anbringen

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-tbaddon#5]
Sofern man die verakteten Mails nicht direkt in Ordner verschiebt, stellt sich die Frage, ob eine Mail bereits in eine Akte transferiert wurde oder nicht - hier kann man schnell den Überblick verlieren. 

Es wäre toll, wenn das Add-On - ähnlich zu den Einstellungen der Etikettierung im j-lawyer - ein sogenanntes "Schlagwort" (so nennt es sich im Thunderbird) an die Mail in Thunderbird anbringen könnte.

**Comment by iradraconis** [comment]
gute Idee

**Comment by iradraconis** [comment]
erledigt :)

**Comment by iradraconis** [comment]
Ich mache nochmal auf, für den Fall, dass hier noch Änderungen rein sollen..

**Comment by j-dimension** [comment]
Super cool!

Er speichert bei mir, bringt das Schlagwort an, dann allerdings auch eine Fehlerausschrift ganz oben in dem kleinen Dialog: Fehler undefined o.ä. 

Ich habe kein Etikett selektiert, nur eine Akte.

**Comment by iradraconis** [comment]
Kann sein weil die Message schon in der Akte ist ?

**Comment by j-dimension** [comment]
Nein, scheint damit nichts zu tun zu haben.

**Comment by iradraconis** [comment]
Müsste man in den Debugger schauen. Die Fehlermeldungen brauchen noch etwas mehr feinschliff.

**Comment by iradraconis** [comment]
Es hilft manchmal auch, Thunderbird neu zu starten, bevor man das Addon installiert. Also alte Version entfernen, neu starten, aktuelle Version installieren, Zugangsdaten eingeben, Daten laden.

**Comment by j-dimension** [comment]
@iradraconis in der Tat! Heute tut es was es soll. Perfekt!
