### ISSUE TITLE
Fehler bei Import von Thunderbird-mails in den Dokumentenordner

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-tbaddon#50]
Der import einer mail in den Dokumentenordner per drag and drop importiert scheinbar die e-mail. Der Inhalt ist aber eine "failed to parse" - errormeldung. Öffnen oder Lesen der Datei nicht möglich.

Der Versuch des Imports mit dem Thunderbirdplugin meldet "Erfolgreich.." aber es erscheint die Datei garnicht im Dokumentenordner. Fehler ist vor 2.7 nie aufgetaucht.

**Comment by iradraconis** [comment]
Ich brauche mehr Infos. Ich kann das nicht nachvollziehen. Und 2.7 ist doch noch gar nicht veröffentlicht.

**Comment by Mucki526** [comment]
Mein Fehler - 2.6.... Tippfehler. Ich habe auf Bitte von Jens das Problem auch hier eingehängt. Hat vermutlich die gleiche Ursache wie der Parsingfehler bei Drag and drop. ...

**Comment by j-dimension** [comment]
Der Parsingfehler ist ein j-lawyer Client-Thema, daher habe ich das Ticket umformuliert und offen gelassen.

**Comment by iradraconis** [comment]
schließe mangels Rückmeldung

**Comment by iradraconis** [comment]
schließe mangels Rückmeldung
