### ISSUE TITLE
Problem mit Plugin

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-tbaddon#51]
Das Plugin funktioniert aber - ich muss immer zweimal den Befehl für das Plugin anklicken, bevor sich das Fenster öffnet. Beim ersten Mal passiert nie was....

**Comment by iradraconis** [comment]
was ist gemeint "den Befehl für das Plugin anklicken"? Es gibt verschiedene Varianten, das Plugin zu bedienen. 
1. Nachrichten Liste
2. Nachrichtenfenster (konkrete eMail)
3. Verfassen-Fenster.

für Nr. 1 ist das Problem bekannt. Das passiert aber meines Wissens nur da und auch nicht immer.

**Comment by iradraconis** [comment]
Die Verwendung des Plugins über dieses Fenster ist immer dann besonders sinnvoll, wenn mehrere E-Mails auf einmal zugeordnet werden sollen. Der Button im Nachrichten Fenster ist zuverlässig und funktioniert immer. Bei dir auch?

**Comment by Mucki526** [comment]
Er funktioniert regelmäßig, wenn ich ihn zweimal anklicke. Manchmal, wenn noch irgendein anderes Fenster im Hintergrund stört nicht. Aber er ist so langsam, dass ich oft entnervt dann doch drag an drop mache... Könnte das Plugin nicht alternativ prüfen, ob s direkt im eigenen Netzwerk zusammen mit dem Server ist ist und dann nicht die mailfunktion nutzen sondern über die "drop and drag" funktion oder vergleichbares (weils da in einem Augenschlag geht)?

**Comment by iradraconis** [comment]
Der Client funktioniert auch nicht, wenn er keine Verbindung zum Server hat. Wenn eine Verbindung zum Server besteht, werden die Nachrichten auch zum Server übertragen. Wenn keine Verbindung besteht, natürlich nicht. 

Das von dir beschriebene Verhalten, dass der Button erst beim zweiten Mal anklicken funktioniert, kann ich so nicht nachvollziehen und das hat auch sonst noch kein Nutzer gemeldet. Kannst du mal ein Video zur Verfügung stellen?

**Comment by Mucki526** [comment]
Hallo, klar, keine Verbindung, keine Übertragung. Aber es muss ja einen technischen Grund dafür geben, dass ich bei Nutzung ds Plugins 15 Sekunden+ auf den Bildschirm schaue, bis die Meldung kommt "Erfolgreich" und bei Drag und Drop in 1 Sekunde die Datei im Client erscheint. Ich ging davon aus, dass das Plugin per e-mail die Datei an den J-lawyer-server schickt. Dann klappt das auch, wenn der Client keine Verbindung zu seinem Server hat, hauptsache man hat e-mail. Daher mein Vorschlag. Aber ich weiss nicht wie das plugin die Datei transportiert.... Vielleicht alles Quatsch was ich da so denke.... :-).

**Comment by j-dimension** [comment]
Das AddOn nutzt eine Schnittstelle, die nur dann verfügbar ist, wenn der j-lawyer Server erreichbar ist. Und je langsamer die Anbindung, umso länger dauert es.

**Comment by iradraconis** [comment]
@Mucki526 was für ein Betriebssystem benutzt du, in welcher Version? Was für einen Computer benutzt du? Falls Windows, benutzt du spezielle Antiviren oder ähnliche Software?

**Comment by Mucki526** [comment]
Wenn es immer die selbe Schnittstelle ist, dann wird bei Nutzung des Plugins die Übertragung ausgebremst. Wie gesagt, die Übertragung mit dem Plugin dauert so lange wie die Versendung einer e-mail mit Anlage und Abspeichern der Kopie, 15sec. Das Drag and Drop ist "Drag and Drop" erledigt. Und da wird die Datei auf dem selben Weg zum Server transportiert. Was bremst dann das Plugin an der Stelle? Das Problem haben wir auf jedem Rechner. Wir benutzen windows 10, jetzt auf einem Rechner windows 11 immer pro. Mein Rechner ist alt. Ich nutze Aviar (free) bei meiner Frau läuft nur der Defender (windows). Auf meinem Rechner laufen "Userbedingt" 1000enderlei Anwendungen, auf dem Lenovo X1 meiner Frau Windows 10 Pro, J-lawyer, libreoffice und Thunderbird und natürlich Firerox und BEA, also nur Minimalausstattung. Ich habe hier nen alten HP, aber aufgerüstet mit Ram und SSD und sonst habe ich Lenovo Yoga 2. Gen und einen 5. gen. 

Mein Rechner (wird bald ausgewechselt, weil nicht windows 11-fähig (Prozessor)
Gerätename	WS13
Prozessor	Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz   3.20 GHz
Installierter RAM	24,0 GB (23,9 GB verwendbar)
Geräte-ID	62116847-ED0A-41F4-BC5F-05B854461462
Produkt-ID	00330-80000-00000-AA261
Systemtyp	64-Bit-Betriebssystem, x64-basierter Prozessor
Stift- und Toucheingabe	Für diese Anzeige ist keine Stift- oder Toucheingabe verfügbar.
Und Samsung SSD

**Comment by iradraconis** [comment]
Ich weiß zwar immer noch nicht, woran es liegt aber der i5 3470 ist 12 Jahre alt! 😮
