### ISSUE TITLE
Standardeinstellung e-mail import - Eingangsdatum

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-tbaddon#53]
Wenn man aus Thunderbird die e-mail importiert erscheint sie mit dem Erstelldatum im Dokumentenordner. Es wäre hilfreich, wenn man voreinstellen könnte (oder als Standard festsetzen), dass die mail mit dem Eingangsdatum im Dokumentenordner abgelegt wird (angezeigt wird das ja im Dokumentenordner mit mouseover... die Info wird also übergeben.... Das j-lawyer-mailprogramm macht das so, das wäre dann nur konsequent.

**Comment by iradraconis** [comment]
Gute Idee, kümmere mich drum

**Comment by iradraconis** [comment]
@Mucki526 Ich habe das Feature umgesetzt in der Version 1.0.2
Es erfolgt ein einautomatisches Update, wenn die Version von den Thunderbird Entwicklern freigegeben wurde. Das kann ein paar Wochen dauern. Bis dahin kann aber auch manuell installiert werden über das Release, das hier bereitgestellt wird.
