### ISSUE TITLE
Aktensuche: "wegen" der Akten in die Suche einbeziehen

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-tbaddon#61]
j-lawyer.IO - API-Erweiterungen in j-lawyer.org 3.0 enthalten:

https://github.com/jlawyerorg/j-lawyer-org/commit/32a70187f57add90304173359a8709fb5f4c3f79

**Comment by iradraconis** [comment]
erledigt via commit [7e8eafa](https://github.com/jlawyerorg/j-lawyer-tbaddon/commit/7e8eafaca57642b1e69d20ce9958c0232f1b983a)

**Comment by j-dimension** [comment]
Großartig!
