### ISSUE TITLE
Vorlagen im Entwurfsfenster: Zeilenumbrüche gehen verloren

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-tbaddon#69]
Der j-lawyer unterstützt sowohl HTML-formatierte als auch plain text-Mailvorlagen. HTML funktioniert wie gewünscht, bei plain text-Vorlagen gehen die Zeilenumbrüche verloren. 

Add-On 1.1.2
j-lawyer 3.0.0.1
macOS
Thunderbird 128.4.2

**Comment by iradraconis** [comment]
Besteht das Problem auch, wenn TB auf "plain/text" umgestellt wird?

**Comment by j-dimension** [comment]
Ja, ich habe vorher "Optionen" - "E-Mail-Format" - "Nur Reintext" gewählt.

**Comment by iradraconis** [comment]
Wird eine Signatur verwendet? 
a.) in jlawyer in plain/text
b.) in jlawyer und als html, 
c.) in TB als plain/text oder 
d.) in TB in HTML?

**Comment by j-dimension** [comment]
Weder in Thunderbird noch im j-lawyer sind Signaturen definiert.
