### ISSUE TITLE
Optionen reagieren nicht

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-tbaddon#7]
Möglicherweise stelle ich mich nur zu dumm an.

Erweiterung ist installiert und erscheint im Thunderbird. Dann auf den Schraubenschlüssel geklickt und ich werde nach Nutzername, Passwort und Serveradresse gefragt.
Server ist eine jL Box im selben Netzwerk, wie der Rechner auf dem TB läuft.
Die eingegebenen Daten sollten korrekt sein. Zweimal kontrolliert.
Der Klick auf Speichern bewirkt nichts. Es bleibt bei der Eingabeaufforderung. Keine Fehlermeldung.
Auch ein Klick auf eine der verlinkten Websites bewirkt nichts. Die Eingabeaufforderung verschwindet und das Fenster in TB bleibt weiß.
Den Server habe ich sowohl mit https als auch ohne eingegeben.

**Comment by iradraconis** [comment]
Es gibt derzeit keine Bestätigung, dass die Eingabe im Optionen Dialog gespeichert wurde. Das kann ich ergänzen. 
Nach Eingabe der Daten bitte wieder in  die Oberfläche des AddOns gehen, auf den Reload Button zweimal klicken. Beim 1. mal klicken werden schon die Daten geladen aber beim 2. Mal klicken sollte sich auch die Liste mit den am Server gespeicherten Etiketten füllen. Das ist ein Indiz dafür, dass alle Daten geladen wurden und das Addon eingerichtet ist. Den "Reload" Button benötigt man nur, wenn es neue Akten gibt, zu denen gespeichert werden soll oder neue Etiketten.

**Comment by Maz111111** [comment]
OK. 
Ich habe nicht verstanden, dass es einen neuen Button in dem Mailfenster gibt und habe irgendwie in der Addon Verwaltung und im Kontextmenu gesucht.
Das sollte in die Beschreibung. Zum Beispiel ein Screenshot.
So, jetzt habe ich den Reloadbutton gefunden. Leider tut sich nichts. Es werden keine Etiketten geladen und AZ werden nicht gefunden.
In welcher Form muss ich den Server eingeben? Mit oder ohne https? Auch nur http bewirkt nichts.
Es wäre also gut, wenn es auch noch die Rückmeldung geben würde, dass eine Verbindung zum Server hergestellt wurde.

**Comment by j-dimension** [comment]
@Maz111111 versuche mal http://IP:8080

(IP ersetzen)

**Comment by iradraconis** [comment]
> OK. Ich habe nicht verstanden, dass es einen neuen Button in dem Mailfenster gibt und habe irgendwie in der Addon Verwaltung und im Kontextmenu gesucht. Das sollte in die Beschreibung. Zum Beispiel ein Screenshot. So, jetzt habe ich den Reloadbutton gefunden. Leider tut sich nichts. Es werden keine Etiketten geladen und AZ werden nicht gefunden. In welcher Form muss ich den Server eingeben? Mit oder ohne https? Auch nur http bewirkt nichts. Es wäre also gut, wenn es auch noch die Rückmeldung geben würde, dass eine Verbindung zum Server hergestellt wurde.

im JLawyer Client befindet sich oben in der Titelleiste die IP-Adresse mit Port. Bsp. 192.168.1.1:8080
vorangestellt muss nur werden "http://" oder "https://"
Bsp. Eingabe des Servers: http://192.168.1.1:8080

Bei der Eingabe der Anmeldedaten im Optionendialog wird noch keine Verbindung zum Server aufgebaut. Das erfolgt erst manuell durch Klicken auf den "Reload" Button.

**Comment by iradraconis** [comment]
Der Button "Speichern" wird nun zu "Login gespeichert" geändert, wenn die Login Daten gespeichert wurden. So erhält der Nutzer ein Feedback.

**Comment by iradraconis** [comment]
> OK. Ich habe nicht verstanden, dass es einen neuen Button in dem Mailfenster gibt und habe irgendwie in der Addon Verwaltung und im Kontextmenu gesucht. Das sollte in die Beschreibung. Zum Beispiel ein Screenshot. So, jetzt habe ich den Reloadbutton gefunden. Leider tut sich nichts. Es werden keine Etiketten geladen und AZ werden nicht gefunden. In welcher Form muss ich den Server eingeben? Mit oder ohne https? Auch nur http bewirkt nichts. Es wäre also gut, wenn es auch noch die Rückmeldung geben würde, dass eine Verbindung zum Server hergestellt wurde.

@Maz111111 hat es geklappt mit einem der Updates?

**Comment by Maz111111** [comment]
Akten werden angezeigt und Etiketten auch.

Wäre nützlich, wenn auch die Aktenetiketten auswählbar wären 

Viele Grüße
Martin
